apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rollouts-canary-demo-vsvc
spec:
  gateways:
  - rollouts-canary-demo-gw
  hosts:
  - rollouts-canary-demo.local.1q77.com
  http:
  - name: primary
    route:
    - destination:
        host: rollouts-canary-demo-svc
      weight: 100
    - destination:
        host: rollouts-canary-demo-preview-svc
      weight: 0
